import React, { useState } from 'react';
import styleSetting from './css/Setting.module.css'

function Setting() {
  return (
    <div className='container'>
      <h1 className='f50 bold darkCharcoal p20'>Setting</h1>
      <hr className="w-full mt20"/>
      <div className={styleSetting.content}>
        <div className={styleSetting.panel}>
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
          fgdhfgh
        </div>
      </div>
    </div>
  )
}

export default Setting